#!/usr/bin/env bash

if ! pidof hyprlock >/dev/null; then
  (
    hyprlock
    ~/.config/hypr/scripts/system-wake
  ) &
fi

# Set keyboard layout to default (first layout)
hyprctl switchxkblayout all 0 > /dev/null 2>&1

if [[ ${LOCK_ONLY:-false} != "true" ]]; then
  (
    sleep 3
    pidof hyprlock >/dev/null || exit 0
    ~/.config/hypr/scripts/brightness-keyboard off
    ~/.config/hypr/scripts/brightness-display off
  ) &
fi
