# Zsh Aliases
alias ls='ls --color=auto'
alias ll='ls -lh'
alias la='ll -A'
alias lg='lazygit'
alias ld='lazydocker'

# Homebrew
export HOMEBREW_BUNDLE_FILE="$HOME/.Brewfile"

# Starship
eval "$(starship init zsh)"
export STARSHIP_CONFIG=~/.config/starship/starship.toml
