general {
    lock_cmd = ~/.config/hypr/scripts/system-lock
    before_sleep_cmd = LOCK_ONLY=true ~/.config/hypr/scripts/system-lock
    after_sleep_cmd = sleep 1 && ~/.config/hypr/scripts/system-wake
    inhibit_sleep = 3
}

listener {
    timeout = 120
    on-timeout = pidof hyprlock || hyprlock
}

listener {
    timeout = 180
    on-timeout = ~/.config/hypr/scripts/system-lock
    on-resume = ~/.config/hypr/scripts/system-wake
}
