general {
    ignore_empty_input = true
}

background {
    monitor =
    color = rgba(26, 27, 38, 1.0)
    path = ~/Pictures/wallpaper.jpg
    blur_passes = 3
}

animations {
    enabled = false
}

input-field {
    monitor =
    size = 650, 100
    position = 0, 0
    halign = center
    valign = center

    inner_color = rgba(26, 27, 38, 0.8)
    outer_color = rgba(169, 177, 214, 1.0)
    outline_thickness = 4

    font_family = JetBrainsMono Nerd Font
    font_color = rgba(169, 177, 214, 1.0)


    placeholder_text = Enter Password
    check_color = rgba(122, 162, 247, 1.0)
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 0
    shadow_passes = 0
    fade_on_empty = false
}

auth {
    fingerprint:enabled = false
}

