# Taps
tap "nikitabobko/tap"

# Formulae
brew "starship"
brew "mas"
brew "lazygit"
brew "lazydocker"
brew "maven"
brew "node@24"
brew "openjdk@21"
brew "mole"
brew "fastfetch"

# Casks
cask "nikitabobko/tap/aerospace"
cask "spotify"
cask "raycast"
cask "ghostty"
cask "obsidian"
cask "vlc"
cask "signal"
cask "whatsapp"
cask "intellij-idea"
cask "brave-browser"
cask "docker-desktop"
cask "font-jetbrains-mono-nerd-font"
cask "font-lilex"
cask "notion"
cask "mullvad-vpn"

# Mac App Store apps
mas "GarageBand", id: 682658836
